before_script:
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
deploy_staging:
  type: deploy
  environment:
    name: staging
    url: discover.manjaro.org
  script:
    - ssh update@discover.manjaro.org 
    - "cd /opt/manjaro/tools/manjaro-applications-discovery 
    - git pull origin master 
    - systemctl stop discover.service 
    - systemctl start discover.service 
    - exit"
  only:
    - master